In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

In [51]:
df = pd.read_csv('C:/Users/USER/Downloads/dataset.csv', index_col=0)
df

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,,,,,,,,,,,,,
63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [52]:
X = df.drop('target', axis=1).to_numpy()
y = df['target'].to_numpy()

In [56]:
#train set, test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [57]:
#데이터 전처리
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [58]:
#SVM 모델
svm_model = SVC(random_state=42)
svm_model.fit(X_train_scaled, y_train)
print(svm_model.score(X_train_scaled, y_train))
print(svm_model.score(X_test_scaled, y_test))

0.9132231404958677
0.8852459016393442

In [64]:
#LR 모델
lr_model = LogisticRegression(random_state=0)
lr_model.fit(X_train_scaled, y_train)
print(lr_model.score(X_train_scaled, y_train))
print(lr_model.score(X_test_scaled, y_test))

0.859504132231405
0.8524590163934426

In [65]:
#DT 모델
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)
print(dt_model.score(X_train, y_train))
print(dt_model.score(X_test, y_test))

1.0
0.8032786885245902

In [66]:
#RF 모델
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
print(rf_model.score(X_train, y_train))
print(rf_model.score(X_test, y_test))

1.0
0.8360655737704918