In [37]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import accuracy_score, classification_report

In [38]:
df = pd.read_csv('C:/Users/USER/Downloads/dataset.csv', index_col=0)
df

,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,,,,,,,,,,,,,
63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [39]:
X = df.drop('trestbps',axis=1)
y = df['trestbps']

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [41]:
#데이터 전처리
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
ss.fit(X_train)
X_train_scaled = ss.transform(X_train)
X_test_scaled = ss.transform(X_test)

In [42]:
svr_model = SVR()
svr_model.fit(X_train_scaled, y_train)
pred_svr = svr_model.predict(X_test_scaled)
print("--------------------Predict-----------------\n", pred_svr)
print(svr_model.score(X_train_scaled, y_train))
mse_svr = np.sqrt(mean_squared_error(pred_svr, y_test))
print('평균제곱근오차', mse_svr)

--------------------Predict-----------------
 [127.08107084 129.02731682 130.17800606 131.18960149 132.74321243
 127.56849715 129.07353687 131.60965865 128.16822964 128.72046774
 126.1489779  129.9687457  128.60289337 126.98321967 128.07892634
 129.68661593 129.10597393 126.65094715 128.12038046 128.11912679
 128.25487731 130.10152744 128.1444687  131.34603546 129.07233981
 126.61291638 128.42074153 129.29985217 130.1880509  129.89246709
 127.54033401 126.99382394 128.13882737 127.71364273 129.26100023
 127.00677473 132.2241275  131.66239814 128.58324713 129.46527039
 131.60695947 127.09722733 130.57900005 128.52557831 127.30467655
 129.72843288 129.71836742 130.35562765 130.68654594 126.5686956
 129.45676328 128.23695496 126.09216676 131.52971154 128.76709492
 131.26869697 130.47410999 126.43391715 130.23644355 128.08722014
 127.4159048  127.48445526 126.72185253 128.58742681 129.87160634
 129.93084215 131.00034498 132.11926295 130.50616256 128.25362293
 128.76015912 126.76816576 128.45778359 129.09731482 128.47112455
 126.44839727]
0.0807295606800763
평균제곱근오차 19.595106826842883

In [44]:
lr_model = LogisticRegression()
lr_model.fit(X_train_scaled, y_train)
pred_lr = lr_model.predict(X_test_scaled)
print("--------------------Predict-----------------\n", pred_lr)
print(lr_model.score(X_train_scaled, y_train))
mse_lr = np.sqrt(mean_squared_error(pred_lr, y_test))
print('평균제곱근오차', mse_lr)

--------------------Predict-----------------
 [110 152 172 140 150 120 130 140 130 130 110 120 130 120 130 130 130 110
 125 120 120 145 110 130 130 124 110 130 125 130 120 140 123 120 120 130
 150 138  94 130 138 120 130 120 120 125 126 130 138 125 125 125 110 130
 130 150 130 120 150 140 120 130 110 120 130 125 130 130 130 126 138 130
 120 130 130 120]
0.3039647577092511
평균제곱근오차 22.824847955912574

In [45]:
dt_model = DecisionTreeRegressor()
dt_model.fit(X_train, y_train)
pred_dt = dt_model.predict(X_test)
print("--------------------Predict-----------------\n", pred_dt)
print(dt_model.score(X_train, y_train))
mse_dt = np.sqrt(mean_squared_error(pred_dt, y_test))
print('평균제곱근오차', mse_dt)

--------------------Predict-----------------
 [110. 138. 125. 150. 136. 118. 138. 138. 140. 110. 130. 160. 180. 124.
 124. 120.  94. 140. 130. 120. 152. 125. 146. 134. 130. 130. 156. 138.
 164. 138. 146. 128. 123. 160. 130. 110. 138. 130. 140. 138. 138. 120.
 140. 120. 130. 108. 150. 130. 138. 100. 108. 120. 110. 174. 125. 112.
 120. 118. 126. 140. 135. 124. 142. 140. 140. 152. 146. 136. 140. 130.
 124. 120. 140. 130. 128. 108.]
1.0
평균제곱근오차 24.180244219740956

In [46]:
rf_model = RandomForestRegressor()
rf_model.fit(X_train, y_train)
pred_rf = rf_model.predict(X_test)
print("--------------------Predict-----------------\n", pred_rf)
print(rf_model.score(X_train, y_train))
mse_rf = np.sqrt(mean_squared_error(pred_rf, y_test))
print('평균제곱근오차', mse_rf)

--------------------Predict-----------------
 [122.65 124.56 131.77 142.32 136.49 126.49 140.13 139.57 135.6  126.3
 124.03 133.49 135.71 126.82 123.06 129.16 123.23 135.3  131.28 127.95
 120.8  145.37 132.67 128.97 132.25 121.98 135.89 131.22 142.26 134.07
 128.75 126.26 130.33 131.74 135.12 125.04 142.26 131.63 122.93 133.45
 130.1  123.38 127.06 124.54 126.28 126.93 142.9  127.56 137.32 120.48
 126.45 131.59 121.3  136.87 128.71 135.19 128.46 125.92 139.01 126.33
 130.69 125.45 127.61 127.5  127.84 150.78 131.79 134.61 132.76 127.75
 137.05 119.29 136.82 126.97 128.15 121.74]
0.8511939472047241
평균제곱근오차 20.41929750325206

In [47]:
knr_model = KNeighborsRegressor()
knr_model.fit(X_train, y_train)
pred_knr = knr_model.predict(X_test)
print("--------------------Predict-----------------\n", pred_knr)
print(knr_model.score(X_train, y_train))
mse_knr = np.sqrt(mean_squared_error(y_test, pred_knr))
print('평균제곱근오차', mse_knr)

--------------------Predict-----------------
 [134.8 125.6 117.6 142.  116.8 130.8 120.2 126.  133.6 147.8 126.2 142.6
 129.6 123.8 122.4 126.  122.8 129.2 126.2 119.8 114.4 140.2 138.  122.8
 129.4 126.4 120.4 124.4 128.  130.2 127.2 118.4 137.2 132.8 141.2 125.
 134.  131.4 119.2 128.  136.  133.6 123.2 125.4 118.6 141.  131.4 118.8
 117.8 124.4 133.6 128.6 123.6 136.  139.  118.4 127.  144.4 125.2 137.2
 132.  124.6 123.2 129.  124.2 135.8 119.8 125.6 119.6 134.4 143.6 126.4
 120.6 126.4 124.8 135.6]
0.2555053210109687
평균제곱근오차 22.58209584231674